# Generated by Django 5.0.3 on 2024-03-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('emergency_contact_no', models.IntegerField()),
                ('do_you_have_any_long_term_insurance', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
                ('reference_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('FeMale', 'FeMale')], max_length=10)),
            ],
        ),
    ]
